# config.yml

backend:
  name: git-gateway
  repo: bleach2004/s-en-r-jekyll
  branch: main
media_folder: "assets/img"
collections:
  - name: "interieur-signing"
    editor:
      preview: false
    label: "Interieur signing"
    folder: "pages/interieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }

  - name: "exterieur-signing"
    editor:
      preview: false
    label: "Exterieur signing"
    folder: "pages/exterieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
