# config.yml

backend:
  name: git-gateway
  repo: bleach2004/s-en-r-jekyll
  branch: main

media_folder: "assets/img/decap"
collections:
  - name: "interieur-signing"
    editor:
      preview: false
    label: "Interieur signing"
    folder: "pages/interieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "carousel_images"
        widget: "list"
        field: { label: Afbeelding, name: image, widget: image }

  - name: "exterieur-signing"
    editor:
      preview: false
    label: "Exterieur signing"
    folder: "pages/exterieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "carousel_images"
        widget: "list"
        field: { label: Afbeelding, name: image, widget: image }

  - label: "Single pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Over ons"
        name: "over-ons"
        file: "pages/over-ons.md"
        fields:
          - { name: title }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Kop 1", name: "kop-1", widget: "string" }
          - { label: "Tekst 1", name: "tekst-1", widget: "string" }
          - { label: "Kop 2", name: "kop-2", widget: "string" }
          - { label: "Tekst 2", name: "tekst-2", widget: "string" }
      - label: "Interieur signing"
        name: "interieur-signing"
        file: "pages/interieur-signing.md"
        fields:
          - { label: "Freesletters", name: "Freesletters", widget: "image" }
          - { label: "LED letters", name: "LED letters", widget: "image" }
          - { label: "Peesframes", name: "Peesframes", widget: "image" }
          - { label: "Lightboxen", name: "Lightboxen", widget: "image" }
          - { label: "Wallcovering", name: "Wallcovering", widget: "image" }
          - { label: "Privacyfolie", name: "Privacyfolie", widget: "image" }
          - {
              label: "Interieurfolie's",
              name: "Interieurfolie's",
              widget: "image",
            }
          - { label: "Meubelrestyle", name: "Meubelrestyle", widget: "image" }
          - {
              label: "Full-color prints",
              name: "Full-color prints",
              widget: "image",
            }
          - {
              label: "Folieteksten en logo's",
              name: "Folieteksten en logo's",
              widget: "image",
            }
          - { label: "Wayfinding", name: "Wayfinding", widget: "image" }
      - label: "Exterieur signing"
        name: "exterieur-signing"
        file: "pages/exterieur-signing.md"
        fields:
          - {
              label: "Gevelbelettering",
              name: "Gevelbelettering",
              widget: "image",
            }
          - { label: "LED letters", name: "LED letters", widget: "image" }
          - { label: "Lichtreclame", name: "Lichtreclame", widget: "image" }
          - { label: "Reclamezuilen", name: "Reclamezuilen", widget: "image" }
          - { label: "Raamstikkers", name: "Raamstikkers", widget: "image" }
          - { label: "Bewegwijzering", name: "Bewegwijzering", widget: "image" }
          - {
              label: "Spandoeken en vlaggen",
              name: "Spandoeken en vlaggen",
              widget: "image",
            }
          - { label: "Fleetmarking", name: "Fleetmarking", widget: "image" }
