# config.yml

backend:
  name: git-gateway
  repo: bleach2004/s-en-r-jekyll
media_folder: "assets/img"
collections:
  - name: "interieur-signing"
    label: "Interieur signing"
    folder: "interieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - {
          name: "carousel_images",
          label: "Carousel Images",
          widget: "list",
          fields: [{ name: "image", label: "Image", widget: "image" }],
        }

  - name: "exterieur-signing"
    label: "Exterieur signing"
    folder: "exterieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - {
          name: "carousel_images",
          label: "Carousel Images",
          widget: "list",
          fields: [{ name: "image", label: "Image", widget: "image" }],
        }
