# config.yml

backend:
  name: git-gateway
  repo: bleach2004/s-en-r-jekyll
  branch: main
media_folder: "assets/img"
collections:
  - name: "interieur-signing"
    editor:
      preview: false
    label: "Interieur signing"
    folder: "pages/interieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "carousel_images"
        widget: "list"
        field: { label: Afbeelding, name: image, widget: image }

  - name: "exterieur-signing"
    editor:
      preview: false
    label: "Exterieur signing"
    folder: "pages/exterieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "carousel_images"
        widget: "list"
        field: { label: Afbeelding, name: image, widget: image }
        
  - name: "single-pages"
    editor:
      preview: false
    label: "Single pages"
    folder: "pages/single-pages"
    fields:
      - { name: title }
      - { label: "Koptekst", name: "header", widget: "string" }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
