# config.yml

backend:
  name: git-gateway
  repo: bleach2004/s-en-r-jekyll
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/img"
collections:
  - name: "interieur-signing"
    label: "Interieur signing"
    folder: "interieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }

  - name: "exterieur-signing"
    label: "Exterieur signing"
    folder: "exterieur-signing"
    fields:
      - { name: title }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
